### PR TITLE
Fix JavaScrip syntax

### PR DESCRIPTION
**Pull request by jorix**
The code JavaScrip has been verified using Closure Compiler to show:
 * undefined vars
 * leaving commas

Syntax problems encountered by the compiler have been fixed.

### CODE REVIEW

**Comment by jmueller17** [comment]
Did you test all these changes? Not sure that the introduction of the var at some places overwrites a global variable?

**Comment by jorix** [comment]
It seems so.

The variables are not used as global in the same source, I have reviewed but the compiler also checks it. 
I also checked is used locally in the function, in almost all cases it is (otherwise I have removed it), and the same name is usually declared as local into other functions in the same source.

Everything points to are oversights, but I have not tested running each js.

**Comment by davidromani** [comment]
How do you test? Are you using testing suites? Which ones?

**Comment by jorix** [comment]
He usado Closure Compiler junto con un código que he escrito para despojar
las paginas PHP con js de todo el php (sirve pero es un poco pedestre)
Lo he publicado en:
  https://github.com/jorix/PHP-Check_js

**Comment by jorix** [comment]
**A Rebase is done** to remove unused `visualization.php` from this PR

**Pull request merged**
